# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 08:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('createtimestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('registrationno', models.CharField(max_length=50, verbose_name='Registration no')),
                ('gstno', models.CharField(max_length=50, verbose_name='GST no')),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('tollfree', models.CharField(blank=True, max_length=25, null=True, verbose_name='Toll-free')),
                ('website', models.CharField(blank=True, max_length=254, null=True)),
                ('payment_bank', models.CharField(blank=True, max_length=254, null=True)),
                ('payment_acc', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashUpReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('cashremaining', models.DecimalField(decimal_places=2, max_digits=30)),
                ('createtimestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create timestamp')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourierVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('formula', models.CharField(max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('identificationno', models.CharField(max_length=50, verbose_name='Registration/IC No')),
                ('address', models.CharField(max_length=254)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch')),
            ],
            options={
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('iscorporate', models.BooleanField()),
                ('iswalkinspecial', models.BooleanField()),
                ('iswalkin', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=25, verbose_name='Invoice No.')),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=254, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=30)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('discountmode', models.CharField(blank=True, max_length=25, null=True, verbose_name='Discount mode')),
                ('gst', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='GST')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('payment', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('createtimestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created datetime')),
                ('updatetimestamp', models.DateTimeField(blank=True, null=True, verbose_name='Update datetime')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=100, verbose_name='Track code')),
                ('skudescription', models.CharField(max_length=255, verbose_name='Description')),
                ('zone', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=25, verbose_name='Weight(kg)')),
                ('dimension_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Dim wt(kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Height(mm)')),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Length(mm)')),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Width(mm)')),
                ('sku', models.CharField(max_length=100)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='GST')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelhubPOS.CourierVendor')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('iscustomer', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True)),
                ('createtimestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create timestamp')),
                ('updatetimestamp', models.DateTimeField(blank=True, null=True, verbose_name='update timestamp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevamount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Previous amount')),
                ('paidamount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Paid amount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('isdocument', models.BooleanField()),
                ('ismerchandise', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=20, unique=True, verbose_name='SKU')),
                ('description', models.CharField(max_length=254)),
                ('zone', models.IntegerField()),
                ('weight_start', models.DecimalField(decimal_places=3, max_digits=30)),
                ('weight_end', models.DecimalField(decimal_places=3, max_digits=30)),
                ('corporate_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('walkin_special_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('walkin_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('updatetimestamp', models.DateTimeField(auto_now=True, verbose_name='master update time')),
                ('couriervendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor', verbose_name='Courier')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ProductType')),
            ],
            options={
                'ordering': ['sku_code'],
            },
        ),
        migrations.CreateModel(
            name='SKUBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('walkin_special_override', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('walkin_override', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('updatetimestamp', models.DateTimeField(auto_now=True, verbose_name='last update timestamp')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelhubPOS.Customer')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.SKU')),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField(verbose_name='Date from')),
                ('dateto', models.DateField(verbose_name='Date to')),
                ('totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Total amt')),
                ('paidamount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Paid amt')),
                ('outstandindamount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Outstanding amt')),
                ('createtimestamp', models.DateTimeField(default=datetime.datetime(2017, 11, 19, 8, 25, 28, 542586, tzinfo=utc), verbose_name='create timestamp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfAccountInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Invoice')),
                ('soa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.StatementOfAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(max_length=25)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'ordering': ['tax_code'],
            },
        ),
        migrations.CreateModel(
            name='UserBranchAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterdata_auth', models.CharField(max_length=20, verbose_name='Master data')),
                ('branch_auth', models.CharField(max_length=20, verbose_name='Branch')),
                ('user_auth', models.CharField(max_length=20, verbose_name='User')),
                ('skupricing_auth', models.CharField(max_length=20, verbose_name='SKU price')),
                ('transaction_auth', models.CharField(max_length=20, verbose_name='Invoice')),
                ('custacc_auth', models.CharField(max_length=20, verbose_name='Cust acc')),
                ('report_auth', models.CharField(max_length=20, verbose_name='Report')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField()),
                ('dateto', models.DateField()),
                ('itemcount', models.PositiveIntegerField()),
                ('createtimestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create timestamp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneDomestic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('postcode_start', models.CharField(max_length=25)),
                ('postcode_end', models.CharField(max_length=25)),
                ('zone', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['zone'],
            },
        ),
        migrations.CreateModel(
            name='ZoneInternational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, unique=True)),
                ('zone_doc', models.PositiveIntegerField(verbose_name='Zone document')),
                ('zone_mer', models.PositiveIntegerField(verbose_name='Zone merchandise')),
                ('couriervendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor', verbose_name='Courier')),
            ],
            options={
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='ZoneType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('isother', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='zonedomestic',
            unique_together=set([('state', 'postcode_start', 'postcode_end')]),
        ),
        migrations.AddField(
            model_name='sku',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Tax'),
        ),
        migrations.AddField(
            model_name='sku',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='producttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ProductType', verbose_name='Product type'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.InvoiceType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.PaymentType'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelhubPOS.CustomerType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='couriervendor',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch'),
        ),
        migrations.AddField(
            model_name='accountreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skubranch',
            unique_together=set([('sku', 'branch', 'customer')]),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('branch', 'invoiceno')]),
        ),
    ]
