# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashUpReportPaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=30)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='*Name')),
                ('isactive', models.BooleanField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountreport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='accountreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vendorreport',
            name='vendor',
        ),
        migrations.RenameField(
            model_name='cashupreport',
            old_name='cashremaining',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='cashupreport',
            name='datefrom',
        ),
        migrations.RemoveField(
            model_name='cashupreport',
            name='dateto',
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='invoicenofrom',
            field=models.CharField(default=0, max_length=100, verbose_name='*Invoice from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='invoicenoto',
            field=models.CharField(default='', max_length=100, verbose_name='*Invoice to'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashupreport',
            name='sessiontimestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 21, 15, 49, 31, 126829), verbose_name='session timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttype',
            name='legend',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='*Legend'),
        ),
        migrations.DeleteModel(
            name='AccountReport',
        ),
        migrations.DeleteModel(
            name='VendorReport',
        ),
        migrations.AddField(
            model_name='cashupreportpaymenttype',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.PaymentType'),
        ),
        migrations.AddField(
            model_name='cashupreportpaymenttype',
            name='repordid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CashUpReport'),
        ),
    ]
