# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_paymenttype',
            field=models.ForeignKey(default='Cash', on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.PaymentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 8, 49, 25, 807792, tzinfo=utc), verbose_name='create timestamp'),
        ),
    ]
