# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0002_auto_20180310_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='identificationno',
            field=models.CharField(max_length=50, verbose_name='*Registration/IC No'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('branch', 'identificationno')]),
        ),
    ]
