# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0002_auto_20171119_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_paymenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.PaymentType'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 8, 51, 7, 562612, tzinfo=utc), verbose_name='create timestamp'),
        ),
    ]
