# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0003_auto_20171119_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinvoice',
            name='remainder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Remainder'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 9, 31, 30, 581201, tzinfo=utc), verbose_name='create timestamp'),
        ),
    ]
