# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-21 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0003_auto_20180121_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashupreport',
            name='invoicenofrom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice from'),
        ),
        migrations.AlterField(
            model_name='cashupreport',
            name='invoicenoto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice to'),
        ),
    ]
