# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0004_auto_20180121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discountvalue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
