# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-12 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0004_auto_20180411_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='statementofaccountinvoice',
            name='invoice',
        ),
        migrations.AddField(
            model_name='statementofaccountinvoice',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='statementofaccountinvoice',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 12), verbose_name='Date from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statementofaccountinvoice',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='statementofaccountinvoice',
            name='description',
            field=models.CharField(default='', max_length=254, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statementofaccountinvoice',
            name='reference',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Terminal', verbose_name='*Terminal'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='datefrom',
            field=models.DateField(blank=True, null=True, verbose_name='Date from'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='outstandindamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Balance'),
        ),
    ]
