# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0004_auto_20171119_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Track code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_paymenttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.PaymentType', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 13, 31, 57, 382883, tzinfo=utc), verbose_name='create timestamp'),
        ),
    ]
