# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0005_auto_20171120_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='addressline1',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='customer',
            name='addressline2',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='line 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='addressline3',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='line 3'),
        ),
        migrations.AddField(
            model_name='customer',
            name='addressline4',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='line 4'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 15, 11, 6, 984920, tzinfo=utc), verbose_name='create timestamp'),
        ),
    ]
