# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0005_invoice_discountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discountvalue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='Discount (RM)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='couriervendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor', verbose_name='*Courier'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight_end',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='*Weight end(kg)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight_start',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='*Weight start(kg)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='zone',
            field=models.IntegerField(blank=True, null=True, verbose_name='*Zone'),
        ),
    ]
