# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 09:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0006_auto_20171122_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 1, 9, 49, 26, 864445, tzinfo=utc), verbose_name='create timestamp'),
        ),
    ]
