# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 15:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0007_auto_20171201_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=254, verbose_name='*Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact',
            field=models.CharField(max_length=25, verbose_name='*Contact'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='*Email'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='gstno',
            field=models.CharField(max_length=50, verbose_name='*GST no'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='owner',
            field=models.CharField(max_length=50, verbose_name='*Owner'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='registrationno',
            field=models.CharField(max_length=50, verbose_name='*Registration no'),
        ),
        migrations.AlterField(
            model_name='couriervendor',
            name='formula',
            field=models.CharField(max_length=254, verbose_name='*Formula'),
        ),
        migrations.AlterField(
            model_name='couriervendor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='couriervendor',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType', verbose_name='*Zone type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch', verbose_name='*Branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=25, verbose_name='*Contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='*Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identificationno',
            field=models.CharField(max_length=50, verbose_name='*Registration/IC No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='*Invoice date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.InvoiceType', verbose_name='*Type'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='producttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ProductType', verbose_name='*Product type'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sku',
            field=models.CharField(max_length=100, verbose_name='*SKU'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='skudescription',
            field=models.CharField(max_length=255, verbose_name='*Description'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=25, null=True, verbose_name='Weight(kg)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='zone',
            field=models.CharField(max_length=100, verbose_name='*Zone'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType', verbose_name='*Zone type'),
        ),
        migrations.AlterField(
            model_name='invoicetype',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Customer', verbose_name='*Customer'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='*Name'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='corporate_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='*Corporate price'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='couriervendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor', verbose_name='*Courier'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='description',
            field=models.CharField(max_length=254, verbose_name='*Description'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ProductType', verbose_name='*Product type'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='sku_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='*SKU'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Tax', verbose_name='*Tax code'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='walkin_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='*Walk in price'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='walkin_special_price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='*Walk in special price'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight_end',
            field=models.DecimalField(decimal_places=3, max_digits=30, verbose_name='*Weight end'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight_start',
            field=models.DecimalField(decimal_places=3, max_digits=30, verbose_name='*Weight start'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='zone',
            field=models.IntegerField(verbose_name='*Zone'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='zone_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType', verbose_name='*Zone type'),
        ),
        migrations.AlterField(
            model_name='skubranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch', verbose_name='*Branch'),
        ),
        migrations.AlterField(
            model_name='skubranch',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.SKU', verbose_name='*SKU'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 5, 15, 6, 50, 337328, tzinfo=utc), verbose_name='create timestamp'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Customer', verbose_name='*Customer'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='datefrom',
            field=models.DateField(verbose_name='*Date from'),
        ),
        migrations.AlterField(
            model_name='statementofaccount',
            name='dateto',
            field=models.DateField(verbose_name='*Date to'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='*GST'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_code',
            field=models.CharField(max_length=25, verbose_name='*Tax code'),
        ),
        migrations.AlterField(
            model_name='userbranchaccess',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.Branch', verbose_name='*Branch'),
        ),
        migrations.AlterField(
            model_name='userbranchaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='*User'),
        ),
        migrations.AlterField(
            model_name='zonedomestic',
            name='postcode_end',
            field=models.CharField(max_length=25, verbose_name='*Postcode end'),
        ),
        migrations.AlterField(
            model_name='zonedomestic',
            name='postcode_start',
            field=models.CharField(max_length=25, verbose_name='*Postcode start'),
        ),
        migrations.AlterField(
            model_name='zonedomestic',
            name='state',
            field=models.CharField(max_length=25, verbose_name='*State'),
        ),
        migrations.AlterField(
            model_name='zonedomestic',
            name='zone',
            field=models.PositiveIntegerField(verbose_name='*Zone'),
        ),
        migrations.AlterField(
            model_name='zoneinternational',
            name='country',
            field=models.CharField(max_length=50, unique=True, verbose_name='*Country'),
        ),
        migrations.AlterField(
            model_name='zoneinternational',
            name='couriervendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor', verbose_name='*Courier'),
        ),
        migrations.AlterField(
            model_name='zoneinternational',
            name='zone_doc',
            field=models.PositiveIntegerField(verbose_name='*Zone document'),
        ),
        migrations.AlterField(
            model_name='zoneinternational',
            name='zone_mer',
            field=models.PositiveIntegerField(verbose_name='*Zone merchandise'),
        ),
    ]
