# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0007_auto_20180428_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='gstno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='GST no'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='payment_acc',
            field=models.CharField(default='-', max_length=254, verbose_name='*Payment acc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='payment_bank',
            field=models.CharField(default='-', max_length=254, verbose_name='*Payment bank'),
            preserve_default=False,
        ),
    ]
