# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0008_auto_20180227_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='courier_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CourierVendor', verbose_name='Default courier'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='zonetype_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.ZoneType', verbose_name='Default zone type'),
        ),
    ]
