# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0009_auto_20180301_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='courier_default',
            new_name='default_courier',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='zonetype_default',
            new_name='default_zonetype',
        ),
    ]
