# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-02 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0009_auto_20180502_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='hasgst',
            field=models.BooleanField(default=True, verbose_name='Has GST'),
            preserve_default=False,
        ),
    ]
