# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0010_auto_20171205_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementofaccount',
            name='createtimestamp',
            field=models.DateTimeField(verbose_name='create timestamp'),
        ),
    ]
