# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0011_auto_20171217_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_lockin_date', models.DateField(verbose_name='*Invoice lock in date')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='customertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parcelhubPOS.CustomerType', verbose_name='*Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight_end',
            field=models.DecimalField(decimal_places=3, max_digits=30, verbose_name='*Weight end(kg)'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight_start',
            field=models.DecimalField(decimal_places=3, max_digits=30, verbose_name='*Weight start(kg)'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='gst',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='*GST(%)'),
        ),
    ]
