# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-01 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0012_auto_20180101_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='is_gst_inclusive',
            field=models.BooleanField(default=False, verbose_name='GST inclusive'),
        ),
    ]
