# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 13:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0016_auto_20180108_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='updatetimestamp',
        ),
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='prevamount',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='branch_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='custacc_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='masterdata_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='report_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='skupricing_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='transaction_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='user_auth',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='*Branch code'),
        ),
        migrations.AddField(
            model_name='userbranchaccess',
            name='access_level',
            field=models.CharField(default='Branch admin', max_length=20, verbose_name='*Access level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='createtimestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='*Invoice datetime'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
