# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0016_auto_20180108_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default='INV', max_length=10, verbose_name='*Branch code'),
            preserve_default=False,
        ),
    ]
