# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0017_auto_20180114_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(default='INV', max_length=10, verbose_name='*Branch code'),
            preserve_default=False,
        ),
    ]
