# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0017_branch_branch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='*Branch code'),
        ),
    ]
