# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0018_auto_20180109_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='branch_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='custacc_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='masterdata_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='report_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='skupricing_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='transaction_auth',
        ),
        migrations.RemoveField(
            model_name='userbranchaccess',
            name='user_auth',
        ),
        migrations.AddField(
            model_name='userbranchaccess',
            name='access_level',
            field=models.CharField(default='Super admin', max_length=20, verbose_name='*Access level'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(max_length=10, verbose_name='*Branch code'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='createtimestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='*Invoice datetime'),
        ),
    ]
