# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0019_auto_20180113_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='updatetimestamp',
        ),
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='prevamount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
