# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-14 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelhubPOS', '0020_auto_20180114_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='*Branch code'),
        ),
    ]
